### ISSUE TITLE
Enabling "Google Authenticator" TOTP 2FA from the user's usermin "Login" settings can fail unexpectedly with undefined Perl subroutine "can_generate_qr"

### ISSUE THREAD

**Issue by nekohayo** [webmin/usermin#116] opened 2024-10-30 16:36 UTC
I don't know if this is already fixed in the development version, so I'm reporting it "in case you haven't previously encountered the bug", based on what's available in the stable versions in your Debian 12 repositories (Usermin 2.102 running on top of Webmin 2.202 + Virtualmin 7.20.2).

---

## Steps to reproduce

Following the instructions from [this forum thread](https://forum.virtualmin.com/t/how-to-set-up-2fa-for-usermin-and-virtualmin-users/113935/5), 2FA was already enabled in "Webmin / Usermin Configuration", however the module was not activated in "Available Modules" in  "Webmin / Usermin Configuration", so I enabled that, and restarted usermin.

Then in my webmail usermin panel, I went to "Login > Two-Factor Authentication" and tried to enable it, and got this confusing  error page, with this error message:

> Enrolling for two-factor authentication with provider Google Authenticator ..  
> .. complete. Your ID with this provider is [some presumably secret ID].
> 
> `HTTP/1.0 500 Perl execution failed Server: MiniServ/2.102 Date: Wed, 30 Oct 2024 15:39:34 GMT Content-type: text/html; Charset=utf-8 Connection: close  `
> `Error — Perl execution failed`
> 
> Undefined subroutine `&twofactor::can_generate_qr` called at `twofactor-funcs-lib.pl` line 235.

![image](https://github.com/user-attachments/assets/949abb53-12c3-42e7-b2fd-e5b04bce737e)

## Analysis and potential solutions

It first claims to have succeeded, then fails (and if I leave and re-enter that page, it seems to not have been enabled, thankfully).

As I understand it, it failed to generate a QR code because of a missing dependency? But as a user, I don't know what to do with this, as I don't have a QR code or clear instructions of what to do with my authenticator app to add this (can I just input that "ID" text string into my auth app? What parameters should I use? etc.)

Ideally, it should:

1. ensure any such dependency is installed by virtualmin/webmin by default, and/or when you enable the feature
2. double-check for the presence of that subroutine before applying the changes to the user in usermin, to avoid any potential of locking them out
3. check that the user is actually capable of generating the matching TOTP codes before fully enabling and enforcing it (if it doesn't already do that)

**Comment by jcameron** [comment] 2024-10-31 04:24
Ah I see the cause of this - we didn't port some of the new QR code generation code over to Usermin. This will be fixed in the next release.

**Closed by jcameron** 2024-10-31 04:24 UTC
